### ISSUE TITLE
allow specifying custom dependencies for files without inferred dependencies

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#3]

**Comment by wizzard0** [comment]
```
modules:
    "app":
        deps: ["lib"]
        format: "rawjs"
    "lib":
        format: "rawjs"

```
